### ISSUE TITLE
Replace `go fmt` with gofumpt

### ISSUE THREAD

**Issue by jadolg** [sladyn98/auto-go-format#2]
[gofumpt](https://github.com/mvdan/gofumpt) Is a super-set of `go fmt` and fixes several more problems (especially annoying extra blank lines and whitespace). Maybe it would be nice to either replace `go fmt` with `gofumpt` or allow it to be parametrized.
Installing `gofumpt` in the `Dockerfile` and replacing this line should do the magic.
https://github.com/sladyn98/auto-go-format/blob/28d4451d4cb75f25d61e55a89323f2d549255a20/entrypoint.sh#L73
What do you think?

**Comment by sladyn98** [comment]
Yeah definitely makes sense

**Comment by jadolg** [comment]
Here's a PR with the changes https://github.com/sladyn98/auto-go-format/pull/4

**Comment by jadolg** [comment]
I'll close this now :smiley: 
Thanks for merging!
